#import <Metal/Metal.h>
#import <Foundation/Foundation.h>
#include <string.h>
#include "../include/metal_backend.h"
#include "../include/render_backend.h"
#include "../include/log.h"
#include "../include/gpu_types.h"
#include "../include/scene.h"

// This code is mostly generated by Claude, because I have no idea about Apple's
// APIs, as well as Objective-C.

@interface HikariMetalCtx : NSObject
@property(nonatomic, strong) id<MTLDevice> device;
@property(nonatomic, strong) id<MTLCommandQueue> queue;
@property(nonatomic, strong) id<MTLComputePipelineState> pipeline;

@property(nonatomic, strong) id<MTLBuffer> vertexBuffer;
@property(nonatomic, strong) id<MTLBuffer> normalBuffer;
@property(nonatomic, strong) id<MTLBuffer> triAttributesBuffer;
@property(nonatomic, strong) id<MTLAccelerationStructure> accelerationStructure;
@end

@implementation HikariMetalCtx
@end

static gpu_v3 to_gpu_v3(v3 v) {
	return (gpu_v3){ (float)v.x, (float)v.y, (float)v.z };
}

metal_ctx* metalInit(void) {
  @autoreleasepool {
    id<MTLDevice> device = MTLCreateSystemDefaultDevice();
    if (!device) {
      print(ERROR, "No Metal device found");
      return NULL;
    }

    NSURL *libraryURL =
        [NSURL fileURLWithPath:@"assets/shaders/shader.metallib"];
    NSError *error = nil;
    id<MTLLibrary> library = [device newLibraryWithURL:libraryURL error:&error];
    if (!library) {
      print(ERROR, "Failed to load shader.metallib: %s",
            [[error localizedDescription] UTF8String]);
      return NULL;
    }

    id<MTLFunction> kernelFunction =
        [library newFunctionWithName:@"render_sample"];
    id<MTLComputePipelineState> pipeline =
        [device newComputePipelineStateWithFunction:kernelFunction
                                              error:&error];
    if (!pipeline) {
      print(ERROR, "Pipeline creation failed: %s",
            [[error localizedDescription] UTF8String]);
      return NULL;
    }

    HikariMetalCtx *ctx = [HikariMetalCtx new];
    ctx.device = device;
    ctx.queue = [device newCommandQueue];
    ctx.pipeline = pipeline;

    print(INFO, "Metal backend initialized on %s", [[device name] UTF8String]);

    return (metal_ctx *)CFBridgingRetain(ctx); // hand ownership to the C side
  }
}

int metalUploadScene(metal_ctx *c_ctx, scene *sc) {
  if (!sc || !c_ctx)
    return -1;

  @autoreleasepool {
    HikariMetalCtx *ctx = (__bridge HikariMetalCtx *)c_ctx;

    // merge mesh into one set of flat buffers
    sz vertexCount = 0, normalCount = 0, triCount = 0;
    for (sz i = 0; i < sc->obj_count; ++i) {
      vertexCount += sc->objects[i].mesh.nverts;
      normalCount += sc->objects[i].mesh.nv_norms;
      triCount += sc->objects[i].mesh.ntris;
    }

    if (triCount == 0) {
      print(WARNING, "Mesh has no triangles");
      return -1;
    }

    gpu_v3* vertices = malloc(vertexCount * sizeof(gpu_v3));
    gpu_v3* normals = malloc(normalCount * sizeof(gpu_v3));
    u32 *indices = malloc(triCount * 3 * sizeof(u32));
    gpu_tri_attrs *triAttributes = malloc(triCount * sizeof(gpu_tri_attrs));

    sz vertexOffset = 0, normalOffset = 0, triOffset = 0;
    for (sz i = 0; i < sc->obj_count; ++i) {
      mesh m = sc->objects[i].mesh;

      for (sz v = 0; v < m.nverts; ++v)
        vertices[v + vertexOffset] = to_gpu_v3(m.verts[v]);

      for (sz n = 0; n < m.nv_norms; ++n)
        normals[n + normalOffset] = to_gpu_v3(m.verts[n]);

      for (sz t = 0; t < m.ntris; ++t) {
        tri tr = m.tris[t];
        sz idx = triOffset + t;

        indices[idx * 3 + 0] = (u32)tr.verts_idx.x + (u32)vertexOffset;
        indices[idx * 3 + 1] = (u32)tr.verts_idx.y + (u32)vertexOffset;
        indices[idx * 3 + 2] = (u32)tr.verts_idx.z + (u32)vertexOffset;

        triAttributes[idx] = (gpu_tri_attrs) {
          .mat_id = (u32)tr.mat_id,
          .n0 = (u32)tr.v_norms_idx.x + (u32)normalOffset,
          .n1 = (u32)tr.v_norms_idx.y + (u32)normalOffset,
          .n2 = (u32)tr.v_norms_idx.z + (u32)normalOffset,
        };
      }

      vertexOffset += m.nverts;
      normalOffset += m.nv_norms;
      triOffset += m.ntris;
    }

    id<MTLDevice> device = ctx.device;
    id<MTLBuffer> vertexBuffer =
        [device newBufferWithBytes:vertices
                            length:vertexCount * sizeof(gpu_v3)
                           options:MTLResourceStorageModeShared];
    id<MTLBuffer> indexBuffer =
        [device newBufferWithBytes:indices
                            length:triCount * 3 * sizeof(u32)
                           options:MTLResourceStorageModeShared];
    id<MTLBuffer> normalBuffer =
        normalCount > 0
            ? [device newBufferWithBytes:normals
                                  length:normalCount * sizeof(gpu_v3)
                                 options:MTLResourceStorageModeShared]
            : nil;
    id<MTLBuffer> triAtttibutesBuffer =
        [device newBufferWithBytes:triAttributes
                            length:triCount * sizeof(gpu_tri_attrs)
                           options:MTLResourceStorageModeShared];

    free(vertices);
    free(normals);
    free(indices);
    free(triAttributes);

    MTLAccelerationStructureTriangleGeometryDescriptor *geometryDescriptor =
        [MTLAccelerationStructureTriangleGeometryDescriptor descriptor];

    geometryDescriptor.vertexBuffer  = vertexBuffer;
    geometryDescriptor.vertexStride  = sizeof(gpu_v3);
    geometryDescriptor.indexBuffer   = indexBuffer;
    geometryDescriptor.indexType     = MTLIndexTypeUInt32;
    geometryDescriptor.triangleCount = triCount;

    MTLPrimitiveAccelerationStructureDescriptor* accelerationStructureDescriptor =
                [MTLPrimitiveAccelerationStructureDescriptor descriptor];
    accelerationStructureDescriptor.geometryDescriptors =
        @[ geometryDescriptor ];

    MTLAccelerationStructureSizes sizes =
        [device accelerationStructureSizesWithDescriptor:accelerationStructureDescriptor];

    id<MTLAccelerationStructure> accelerationStructure = [device
        newAccelerationStructureWithSize:sizes.accelerationStructureSize];

    id<MTLBuffer> scratch =
        [device newBufferWithLength:sizes.buildScratchBufferSize
                            options:MTLResourceStorageModePrivate];

    id<MTLCommandBuffer> commandBuffer = [ctx.queue commandBuffer];
    id<MTLAccelerationStructureCommandEncoder> commandEncoder =
        [commandBuffer accelerationStructureCommandEncoder];

    [commandEncoder buildAccelerationStructure:accelerationStructure
                                    descriptor:accelerationStructureDescriptor
                                 scratchBuffer:scratch
                           scratchBufferOffset:0];

    [commandEncoder endEncoding];
    [commandBuffer commit];
    [commandBuffer waitUntilCompleted];

    ctx.vertexBuffer = vertexBuffer;
    ctx.normalBuffer = normalBuffer;
    ctx.triAttributesBuffer = triAtttibutesBuffer;
    ctx.accelerationStructure = accelerationStructure;

    print(INFO, "Uploaded %zu verts / %zu tris, acceleration structure built", vertexCount, triCount);
    return 0;
  }
}

void metalRenderSample(metal_ctx* c_ctx, render_args renderArguments, uint32_t sampleNumber) {
  if (!c_ctx)
    return;

  @autoreleasepool {
    HikariMetalCtx *ctx = (__bridge HikariMetalCtx *)c_ctx;

    if (!ctx.accelerationStructure) {
      print(ERROR, "metal_render_sample: no scene uploaded, call "
                   "metal_upload_scene first");
      return;
    }

    gpu_camera gpuCamera = {
        .origin = to_gpu_v3(renderArguments.cam.origin),
        .lower_left = to_gpu_v3(renderArguments.cam.lower_left),
        .horizontal = to_gpu_v3(renderArguments.cam.horizontal),
        .vertical = to_gpu_v3(renderArguments.cam.vertical)};


    sz imageBytesCount =
        renderArguments.width * renderArguments.height * 3 * sizeof(f32);
    gpu_args gpuArguments = {.width = renderArguments.width,
                             .height = renderArguments.height,
                             .cam = gpuCamera};

    id<MTLBuffer> imageBuffer =
        [ctx.device newBufferWithBytes:renderArguments.img
                                length:imageBytesCount
                               options:MTLResourceStorageModeShared];
    id<MTLBuffer> renderArgumentsBuffer =
        [ctx.device newBufferWithBytes:&gpuArguments
                                length:sizeof(gpu_args)
                               options:MTLResourceStorageModeShared];
    id<MTLBuffer> sampleNumberBuffer =
        [ctx.device newBufferWithBytes:&sampleNumber
                                length:sizeof(sampleNumber)
                               options:MTLResourceStorageModeShared];


    id<MTLCommandBuffer> commandBuffer = [ctx.queue commandBuffer];
    id<MTLComputeCommandEncoder> commandEncoder =
        [commandBuffer computeCommandEncoder];

    [commandEncoder setComputePipelineState:ctx.pipeline];
    [commandEncoder setBuffer:imageBuffer offset:0 atIndex:0];
    [commandEncoder setBuffer:renderArgumentsBuffer offset:0 atIndex:1];
    [commandEncoder setBuffer:sampleNumberBuffer offset:0 atIndex:2];
    [commandEncoder setAccelerationStructure:ctx.accelerationStructure
                               atBufferIndex:3];
    [commandEncoder setBuffer:ctx.triAttributesBuffer offset:0 atIndex:5];

    MTLSize grid =
        MTLSizeMake(renderArguments.width, renderArguments.height, 1);
    NSUInteger tw = ctx.pipeline.threadExecutionWidth;
    NSUInteger th = ctx.pipeline.maxTotalThreadsPerThreadgroup / tw;
    MTLSize threadgroup = MTLSizeMake(tw, th, 1);

    [commandEncoder dispatchThreads:grid threadsPerThreadgroup:threadgroup];
    [commandEncoder endEncoding];
    [commandBuffer commit];
    [commandBuffer waitUntilCompleted];

    memcpy(renderArguments.img, imageBuffer.contents, imageBytesCount);
  }
}

void metalShutdown(metal_ctx* c_ctx) {
  if (c_ctx)
    CFBridgingRelease(c_ctx);
}
