#import <Metal/Metal.h>
#import <Foundation/Foundation.h>
#include <string.h>
#include "../include/metal_backend.h"
#include "../include/render_backend.h"
#include "../include/log.h"
#include "../include/gpu_types.h"
#include "../include/scene.h"
#include "../include/settings.h"

// This code is mostly generated by Claude, because I have no idea about Apple's
// APIs, as well as Objective-C.




@interface HikariMetalCtx : NSObject
@property(nonatomic, strong) id<MTLDevice> device;
@property(nonatomic, strong) id<MTLCommandQueue> queue;
@property(nonatomic, strong) id<MTLComputePipelineState> pipeline;

@property(nonatomic, strong) id<MTLBuffer> materialBuffer;
@property(nonatomic, strong) id<MTLBuffer> nodeBuffer;
@property(nonatomic, strong) id<MTLBuffer> socketBuffer;

@property(nonatomic, strong) id<MTLBuffer> vertexBuffer;
@property(nonatomic, strong) id<MTLBuffer> normalBuffer;
@property(nonatomic, strong) id<MTLBuffer> triAttributesBuffer;
@property(nonatomic, strong) id<MTLAccelerationStructure> accelerationStructure;
@end

@implementation HikariMetalCtx
@end

static gpu_v3 to_gpu_v3(v3 v) {
	return (gpu_v3){ (float)v.x, (float)v.y, (float)v.z };
}
static gpu_v3 gpu_v3_sub(gpu_v3 a, gpu_v3 b) {
  return (gpu_v3){a.x - b.x, a.y - b.y, a.z - b.z};
}
static gpu_v3 gpu_v3_cross(gpu_v3 a, gpu_v3 b) {
  return (gpu_v3){a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z,
                  a.x * b.y - a.y * b.x};
}
static gpu_v3 gpu_v3_norm(gpu_v3 v) {
  float len = sqrtf(v.x * v.x + v.y * v.y + v.z * v.z);
  return (gpu_v3){v.x / len, v.y / len, v.z / len};
}

static gpu_mat to_gpu_mat(mat m) {
  return (gpu_mat){.root_socket = m.root_socket};
}

static gpu_mat_node to_gpu_node(mat_node n) {
  gpu_mat_node_value_type t = (gpu_mat_node_value_type)n.out_type;
  gpu_mat_node_value_data d;

  if (t == GPU_NV_FLOAT)
    d.value = (float)n.out_data.value;
  else if (t == GPU_NV_COLOUR)
    d.v3 = to_gpu_v3(n.out_data.v3);
  else
    d.value = 0;

  return (gpu_mat_node){.type = (gpu_mat_node_type)n.type,
                        .out_type = t,
                        .out_data = d,
                        .input_count = n.input_count,
                        .input_start = n.input_start};
}

static gpu_mat_node_socket to_gpu_socket(mat_node_socket s) {
  gpu_mat_node_value_type t = (gpu_mat_node_value_type)s.type;
  gpu_mat_node_value_data d;

  if (t == GPU_NV_FLOAT)
    d.value = (float)s.data.value;
  else if (t == GPU_NV_COLOUR)
    d.v3 = to_gpu_v3(s.data.v3);
  else
    d.value = 0;

  return (gpu_mat_node_socket){.type = t, .data = d, .link = s.link};
}

metal_ctx* metalInit(void) {
  @autoreleasepool {
    id<MTLDevice> device = MTLCreateSystemDefaultDevice();
    if (!device) {
      print(ERROR, "No Metal device found");
      return NULL;
    }

    NSURL *libraryURL =
        [NSURL fileURLWithPath:@"assets/shaders/shader.metallib"];
    NSError *error = nil;
    id<MTLLibrary> library = [device newLibraryWithURL:libraryURL error:&error];
    if (!library) {
      print(ERROR, "Failed to load shader.metallib: %s",
            [[error localizedDescription] UTF8String]);
      return NULL;
    }

    id<MTLFunction> kernelFunction =
        [library newFunctionWithName:@"render_sample"];
    id<MTLComputePipelineState> pipeline =
        [device newComputePipelineStateWithFunction:kernelFunction
                                              error:&error];
    if (!pipeline) {
      print(ERROR, "Pipeline creation failed: %s",
            [[error localizedDescription] UTF8String]);
      return NULL;
    }

    HikariMetalCtx *ctx = [HikariMetalCtx new];
    ctx.device = device;
    ctx.queue = [device newCommandQueue];
    ctx.pipeline = pipeline;

    print(INFO, "Metal backend initialized on %s", [[device name] UTF8String]);

    return (metal_ctx *)CFBridgingRetain(ctx); // hand ownership to the C side
  }
}

int metalUploadScene(metal_ctx *c_ctx, scene *sc) {
  if (!sc || !c_ctx)
    return -1;

  @autoreleasepool {
    HikariMetalCtx *ctx = (__bridge HikariMetalCtx *)c_ctx;

    // merge mesh into one set of flat buffers
    sz vertexCount = 0, normalCount = 0, triCount = 0;
    for (sz i = 0; i < sc->obj_count; ++i) {
      vertexCount += sc->objects[i].mesh.nverts;
      normalCount += sc->objects[i].mesh.nv_norms;
      triCount += sc->objects[i].mesh.ntris;
    }

    if (triCount == 0) {
      print(WARNING, "Mesh has no triangles");
      return -1;
    }

    gpu_v3* vertices = malloc(vertexCount * sizeof(gpu_v3));
    gpu_v3* normals = malloc(normalCount * sizeof(gpu_v3));
    u32 *indices = malloc(triCount * 3 * sizeof(u32));
    gpu_tri_attrs *triAttributes = malloc(triCount * sizeof(gpu_tri_attrs));

    sz vertexOffset = 0, normalOffset = 0, triOffset = 0;
    for (sz i = 0; i < sc->obj_count; ++i) {
      mesh m = sc->objects[i].mesh;

      for (sz v = 0; v < m.nverts; ++v)
        vertices[v + vertexOffset] = to_gpu_v3(m.verts[v]);

      for (sz n = 0; n < m.nv_norms; ++n)
        normals[n + normalOffset] = to_gpu_v3(m.v_norms[n]);

      for (sz t = 0; t < m.ntris; ++t) {
        tri tri = m.tris[t];
        sz idx = triOffset + t;

        indices[idx * 3 + 0] = (u32)tri.verts_idx.x + (u32)vertexOffset;
        indices[idx * 3 + 1] = (u32)tri.verts_idx.y + (u32)vertexOffset;
        indices[idx * 3 + 2] = (u32)tri.verts_idx.z + (u32)vertexOffset;

        gpu_v3 p0 = vertices[indices[idx * 3 + 0]];
        gpu_v3 p1 = vertices[indices[idx * 3 + 1]];
        gpu_v3 p2 = vertices[indices[idx * 3 + 2]];
        gpu_v3 true_normal = gpu_v3_norm(gpu_v3_cross(gpu_v3_sub(p1, p0), gpu_v3_sub(p2, p0)));

        triAttributes[idx] = (gpu_tri_attrs){
            .mat_id = (u32)tri.mat_id,
            .n0 = (u32)tri.v_norms_idx.x + (u32)normalOffset,
            .n1 = (u32)tri.v_norms_idx.y + (u32)normalOffset,
            .n2 = (u32)tri.v_norms_idx.z + (u32)normalOffset,
            .true_normal = true_normal,
        };
      }

      vertexOffset += m.nverts;
      normalOffset += m.nv_norms;
      triOffset += m.ntris;
    }

    // make material buffers
    sz meterialCount = sc->mat_lib->mat_count;
    sz nodeCount = sc->mat_lib->node_count;
    sz socketCount = sc->mat_lib->socket_count;
    gpu_mat *materials = malloc(meterialCount * sizeof(gpu_mat));
    gpu_mat_node *nodes = malloc(nodeCount * sizeof(gpu_mat_node));
    gpu_mat_node_socket *sockets =
        malloc(socketCount * sizeof(gpu_mat_node_socket));

    for (sz i = 0; i < meterialCount; ++i) {
      materials[i] = to_gpu_mat(sc->mat_lib->materials[i]);
    }
    for (sz i = 0; i < nodeCount; ++i) {
      nodes[i] = to_gpu_node(sc->mat_lib->nodes[i]);
    }
    for (sz i = 0; i < socketCount; ++i) {
      sockets[i] = to_gpu_socket(sc->mat_lib->sockets[i]);
    }


    id<MTLDevice> device = ctx.device;
    id<MTLBuffer> vertexBuffer =
        [device newBufferWithBytes:vertices
                            length:vertexCount * sizeof(gpu_v3)
                           options:MTLResourceStorageModeShared];
    id<MTLBuffer> indexBuffer =
        [device newBufferWithBytes:indices
                            length:triCount * 3 * sizeof(u32)
                           options:MTLResourceStorageModeShared];
    id<MTLBuffer> normalBuffer =
        normalCount > 0
            ? [device newBufferWithBytes:normals
                                  length:normalCount * sizeof(gpu_v3)
                                 options:MTLResourceStorageModeShared]
            : nil;
    id<MTLBuffer> triAtttibutesBuffer =
        [device newBufferWithBytes:triAttributes
                            length:triCount * sizeof(gpu_tri_attrs)
                           options:MTLResourceStorageModeShared];
    id<MTLBuffer> materialBuffer =
        [device newBufferWithBytes:materials
                            length:meterialCount * sizeof(gpu_mat)
                           options:MTLResourceStorageModeShared];
    id<MTLBuffer> nodeBuffer =
        [device newBufferWithBytes:nodes
                            length:nodeCount * sizeof(gpu_mat_node)
                           options:MTLResourceStorageModeShared];
    id<MTLBuffer> socketBuffer =
        [device newBufferWithBytes:sockets
                            length:socketCount * sizeof(gpu_mat_node_socket)
                           options:MTLResourceStorageModeShared];

    free(vertices);
    free(normals);
    free(indices);
    free(triAttributes);
    free(materials);
    free(nodes);
    free(sockets);

    MTLAccelerationStructureTriangleGeometryDescriptor *geometryDescriptor =
        [MTLAccelerationStructureTriangleGeometryDescriptor descriptor];

    geometryDescriptor.vertexBuffer  = vertexBuffer;
    geometryDescriptor.vertexStride  = sizeof(gpu_v3);
    geometryDescriptor.indexBuffer   = indexBuffer;
    geometryDescriptor.indexType     = MTLIndexTypeUInt32;
    geometryDescriptor.triangleCount = triCount;

    MTLPrimitiveAccelerationStructureDescriptor* accelerationStructureDescriptor =
                [MTLPrimitiveAccelerationStructureDescriptor descriptor];
    accelerationStructureDescriptor.geometryDescriptors =
        @[ geometryDescriptor ];

    MTLAccelerationStructureSizes sizes =
        [device accelerationStructureSizesWithDescriptor:accelerationStructureDescriptor];

    id<MTLAccelerationStructure> accelerationStructure = [device
        newAccelerationStructureWithSize:sizes.accelerationStructureSize];

    id<MTLBuffer> scratch =
        [device newBufferWithLength:sizes.buildScratchBufferSize
                            options:MTLResourceStorageModePrivate];

    id<MTLCommandBuffer> commandBuffer = [ctx.queue commandBuffer];
    id<MTLAccelerationStructureCommandEncoder> commandEncoder =
        [commandBuffer accelerationStructureCommandEncoder];

    [commandEncoder buildAccelerationStructure:accelerationStructure
                                    descriptor:accelerationStructureDescriptor
                                 scratchBuffer:scratch
                           scratchBufferOffset:0];

    [commandEncoder endEncoding];
    [commandBuffer commit];
    [commandBuffer waitUntilCompleted];

    ctx.vertexBuffer = vertexBuffer;
    ctx.normalBuffer = normalBuffer;
    ctx.triAttributesBuffer = triAtttibutesBuffer;
    ctx.accelerationStructure = accelerationStructure;
    ctx.materialBuffer = materialBuffer;
    ctx.nodeBuffer = nodeBuffer;
    ctx.socketBuffer = socketBuffer;

    print(INFO, "Uploaded %zu verts / %zu tris, acceleration structure built", vertexCount, triCount);
    return 0;
  }
}

void metalRenderSample(metal_ctx* c_ctx, render_args renderArguments, uint32_t sampleNumber) {
  if (!c_ctx)
    return;

  @autoreleasepool {
    HikariMetalCtx *ctx = (__bridge HikariMetalCtx *)c_ctx;

    if (!ctx.accelerationStructure) {
      print(ERROR, "metal_render_sample: no scene uploaded, call "
                   "metal_upload_scene first");
      return;
    }

    gpu_camera gpuCamera = {
        .origin = to_gpu_v3(renderArguments.cam.origin),
        .lower_left = to_gpu_v3(renderArguments.cam.lower_left),
        .horizontal = to_gpu_v3(renderArguments.cam.horizontal),
        .vertical = to_gpu_v3(renderArguments.cam.vertical)};


    sz imageBytesCount =
        renderArguments.width * renderArguments.height * 3 * sizeof(f32);
    gpu_args gpuArguments = {.width = renderArguments.width,
                             .height = renderArguments.height,
                             .cam = gpuCamera};

    id<MTLBuffer> imageBuffer =
        [ctx.device newBufferWithBytes:renderArguments.img
                                length:imageBytesCount
                               options:MTLResourceStorageModeShared];
    id<MTLBuffer> renderArgumentsBuffer =
        [ctx.device newBufferWithBytes:&gpuArguments
                                length:sizeof(gpu_args)
                               options:MTLResourceStorageModeShared];
    id<MTLBuffer> sampleNumberBuffer =
        [ctx.device newBufferWithBytes:&sampleNumber
                                length:sizeof(sampleNumber)
                               options:MTLResourceStorageModeShared];


    id<MTLCommandBuffer> commandBuffer = [ctx.queue commandBuffer];
    id<MTLComputeCommandEncoder> commandEncoder =
        [commandBuffer computeCommandEncoder];

    [commandEncoder setComputePipelineState:ctx.pipeline];
    [commandEncoder setBuffer:imageBuffer offset:0 atIndex:0];
    [commandEncoder setBuffer:renderArgumentsBuffer offset:0 atIndex:1];
    [commandEncoder setBuffer:sampleNumberBuffer offset:0 atIndex:2];
    [commandEncoder setAccelerationStructure:ctx.accelerationStructure
                               atBufferIndex:3];
    if (ctx.normalBuffer)
      [commandEncoder setBuffer:ctx.normalBuffer offset:0 atIndex:4];
    [commandEncoder setBuffer:ctx.triAttributesBuffer offset:0 atIndex:5];

    [commandEncoder setBuffer:ctx.materialBuffer offset:0 atIndex:6];
    [commandEncoder setBuffer:ctx.nodeBuffer offset:0 atIndex:7];
    [commandEncoder setBuffer:ctx.socketBuffer offset:0 atIndex:8];

    MTLSize grid =
        MTLSizeMake(renderArguments.width, renderArguments.height, 1);
    NSUInteger tw = ctx.pipeline.threadExecutionWidth;
    NSUInteger th = ctx.pipeline.maxTotalThreadsPerThreadgroup / tw;
    MTLSize threadgroup = MTLSizeMake(tw, th, 1);

    [commandEncoder dispatchThreads:grid threadsPerThreadgroup:threadgroup];
    [commandEncoder endEncoding];
    [commandBuffer commit];
    [commandBuffer waitUntilCompleted];

    memcpy(renderArguments.img, imageBuffer.contents, imageBytesCount);
  }
}

void metalShutdown(metal_ctx* c_ctx) {
  if (c_ctx)
    CFBridgingRelease(c_ctx);
}

static int metal_backend_init(render_args* args) {
	metal_ctx* ctx = metalInit();
	if (!ctx) return -1;
	if (metalUploadScene(ctx, &args->scene) != 0) {
		metalShutdown(ctx);
		return -1;
	}
	args->ctx = ctx;
	return 0;
}

static void metal_backend_render(render_args* args) {
	struct timespec t0, t1;
	clock_gettime(CLOCK_MONOTONIC, &t0);
	for (sz i = 0; i < N_SAMPLES; ++i) {
		if (args->state->should_stop) break;
		metalRenderSample((metal_ctx*)args->ctx, *args, i);
		args->state->samples_done = i + 1;
	}
	clock_gettime(CLOCK_MONOTONIC, &t1);
	print(INFO, "Rendered in %.3f s.", (t1.tv_sec - t0.tv_sec) + (t1.tv_nsec - t0.tv_nsec) * 1e-9);
}

static void metal_backend_shutdown(render_args* args) {
	if (args->ctx) metalShutdown((metal_ctx*)args->ctx);
	args->ctx = NULL;
}

const render_backend metal_backend_ops = {
	.name = "metal",
	.init = metal_backend_init,
	.render = metal_backend_render,
	.shutdown = metal_backend_shutdown
};
